<a href="https://colab.research.google.com/github/Deltan2002/pytorch/blob/main/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [13]:
x = torch.randn(3,requires_grad=True)
x

tensor([-0.6041, -0.5312,  0.6766], requires_grad=True)

In [39]:
y = x + 2
print(y)

z = y*y*2
print('z:',z)

# z = z.mean()
print('z mean:', z)

tensor([1.3959, 1.4688, 2.6766], grad_fn=<AddBackward0>)
z: tensor([ 3.8969,  4.3146, 14.3289], grad_fn=<MulBackward0>)
z mean: tensor([ 3.8969,  4.3146, 14.3289], grad_fn=<MulBackward0>)


In [40]:
vector = torch.tensor([0.1, 1.0, 0.001],dtype=torch.float32)

z.backward(vector) #dz/dx
print(x.grad)

tensor([ 5.2113, 37.2090,  3.6331], grad_fn=<AddBackward0>)


In [47]:
# PREVENTING GRADIENT HISTORY

# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

x.requires_grad_(False)    #whenever a function has a trailing underscore, then that means it modifies in-place
print(x)

y = x.detach()
print(y)

with torch.no_grad():
  y = x+2
  print(y)

tensor([-0.6041, -0.5312,  0.6766])
tensor([-0.6041, -0.5312,  0.6766])
tensor([1.3959, 1.4688, 2.6766])


In [58]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights * 3).sum()
  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


Whenever we want to calculate the gradients we must specify the **requires_grad=True**, then we can calucalte gradients by calling **backward()** function and before we move on to next iteration, we must empty our gradients by calling **weights.grad.zero_()**