<a href="https://colab.research.google.com/github/Deltan2002/pytorch/blob/main/tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch


In [15]:
x = torch.empty(2,2)
x

tensor([[2.3205e-02, 3.1735e-41],
        [2.3018e-02, 3.1735e-41]])

In [16]:
x = torch.rand(2,2)
x

tensor([[0.5865, 0.3573],
        [0.3434, 0.4016]])

In [18]:
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [21]:
x = torch.ones(2,2)
x
print(x.dtype)

torch.float32


In [25]:
x = torch.ones(2,2,dtype=torch.double)
print(x.dtype)
print(x.size())

torch.float64
torch.Size([2, 2])


In [26]:
x = torch.tensor([2.3,0.1])
x

tensor([2.3000, 0.1000])

In [43]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

# z = x+y
# a = torch.add(x,y)
# print()
# print(a)
# print(z)

# print()

# y.add_(x)  #inplace addition,modifies y
# print(y)



##### subtract

# z = x-y
# a = torch.sub(x,y)
# print(z)
# print(a)
# print()

# y.sub_(x)
# print(y)


# mul, div

tensor([[0.9273, 0.5544],
        [0.4011, 0.1706]])
tensor([[0.3861, 0.1418],
        [0.9570, 0.7355]])
tensor([[-0.5413, -0.4126],
        [ 0.5559,  0.5649]])


In [50]:
x = torch.rand(5,3)
print(x)
print(x[:,0]) # all rows, but only first column [indexing from 0]
print(x[1,:]) # second row, all cols
print(x[1,1])
print(x[1,1].item()) #gives actual value



tensor([[0.4621, 0.9482, 0.5305],
        [0.9270, 0.9701, 0.3263],
        [0.5192, 0.5657, 0.4723],
        [0.9239, 0.0769, 0.5973],
        [0.5776, 0.1914, 0.9071]])
tensor([0.4621, 0.9270, 0.5192, 0.9239, 0.5776])
tensor([0.9270, 0.9701, 0.3263])
tensor(0.9701)
0.9701188802719116


In [63]:
#reshaping

x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)
print(y.size())
print()


y = x.view(-1,8)
print(y)
print(y.size())



tensor([[0.8812, 0.5028, 0.7499, 0.0895],
        [0.1948, 0.0399, 0.9609, 0.8579],
        [0.1330, 0.2945, 0.4310, 0.9879],
        [0.9941, 0.7354, 0.8814, 0.1104]])
tensor([0.8812, 0.5028, 0.7499, 0.0895, 0.1948, 0.0399, 0.9609, 0.8579, 0.1330,
        0.2945, 0.4310, 0.9879, 0.9941, 0.7354, 0.8814, 0.1104])
torch.Size([16])

tensor([[0.8812, 0.5028, 0.7499, 0.0895, 0.1948, 0.0399, 0.9609, 0.8579],
        [0.1330, 0.2945, 0.4310, 0.9879, 0.9941, 0.7354, 0.8814, 0.1104]])
torch.Size([2, 8])


In [69]:
#converting numpy array to tensor and vice versa
import numpy as np
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(b))

print("#############")
a  = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
print(b.dtype)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
#############
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
torch.float64
